application: returngerald
version: 1
runtime: python27
api_version: 1
threadsafe: true

  
libraries:
- name: jinja2
  version: latest


handlers:
- url: /favicon.ico
  static_files: premise/assets/favicon.ico
  upload: premise/assets/favicon.ico

- url: /robots.txt
  static_files: premise/assets/robots.txt
  upload: premise/assets/robots.txt

- url: /assets
  static_dir: premise/assets

- url: /.*
  script: premise.app

